language: node_js
node_js:
 - "11.10.1"
install:
 - npm install
before_script:
 - export COVERAGE_TOKEN=$COVERAGE_TOKEN
script:
 - npm run write-coveralls
 - npm test

# language: node_js
# node_js:
#   - "11.10.1"
# deploy:
#   provider: heroku
#   api_key: $HEROKU_KEY
#   app: pursuit-fruitsapp-qc
#   on: master
#   strategy: git